# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-23 05:15
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superware', '0002_auto_20180502_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='metodoPago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='superware.MetodoPago'),
        ),
    ]
